//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabosPacsUpdater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GABOS\\Services\\WadoRS")]
        public string LocalPathWadoRS {
            get {
                return ((string)(this["LocalPathWadoRS"]));
            }
            set {
                this["LocalPathWadoRS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GABOS\\Services\\Dimse")]
        public string LocalPathDimse {
            get {
                return ((string)(this["LocalPathDimse"]));
            }
            set {
                this["LocalPathDimse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GABOS\\Services\\Hangfire")]
        public string LocalPathHangfire {
            get {
                return ((string)(this["LocalPathHangfire"]));
            }
            set {
                this["LocalPathHangfire"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gabospl-my.sharepoint.com/:f:/g/personal/rmajewski_gabos_pl1/Ev2SZgQrYdhD" +
            "qiGLwI9IoJ4B0a2P26rMAbXU_SWYBghRHQ?e=qrOP8E")]
        public string RemotePathWadoRS {
            get {
                return ((string)(this["RemotePathWadoRS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gabospl-my.sharepoint.com/:f:/g/personal/rmajewski_gabos_pl1/EpZaqAG2lc9H" +
            "lafQ2T0BUgQBKu6goQZqSYpldDO2Bi9Kpw?e=meDe6r")]
        public string RemotePathDimse {
            get {
                return ((string)(this["RemotePathDimse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gabospl-my.sharepoint.com/:f:/g/personal/rmajewski_gabos_pl1/EqUT5v4mdp1I" +
            "m2fCXgiXEuABkMVjimRVH-CHnWyElTcS7g?e=qxYhzq")]
        public string RemotePathHangfire {
            get {
                return ((string)(this["RemotePathHangfire"]));
            }
        }
    }
}
